communaute:
    resource: "@CommunauteBundle/Resources/config/routing.yml"
    prefix:   /

plants:
    resource: "@PlantsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
