plants_homepage:
    path:     /home
    defaults: { _controller: PlantsBundle:Default:index }

plants_inscription:
    path:     /inscription
    defaults: { _controller: PlantsBundle:User:adduser }
